name: CI con pytest

on: [push, pull_request]  # Se ejecuta al hacer push o PR

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Descarga tu código
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run tests with pytest
        run: |
          pytest tests/ -v  # Ejecuta todas las pruebas